### ISSUE TITLE
How to control ionic ion drawer  --> hide & show in different pages

### ISSUE THREAD

**Issue by iiitmahesh** [driftyco/ionic-ion-drawer#22]
how to make ionic.drawer show in one page and hide another page.(control drawer with my controller )

My requirement : Sign in page should not drawer and but other pages should contain it

 side menu drawer is starting with app using state provider (abstract: true)

I've tried this (but it is not working )
drawer side="left" canDrag="true"
drawer side="left" canDrag="false"

**Comment by Ionitron** [comment]
Greetings @iiitmahesh!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
